import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../style/globals.css';
import { headers } from 'next/headers';
import { AppWrapper } from '@/context/AppContext';

const fontSuit = localFont({
    src: '../../public/fonts/SUIT/SUIT-Medium.woff2',
    variable: '--font-suit',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = await headers();
    const userAgent = headersList.get('user-agent') || '';
    const isMobile = /Mobile|Android|iP(hone|od|ad)|IEMobile|BlackBerry/i.test(userAgent);

    return (
        <html lang="ko">
            <body className={`${isMobile ? 'mobile' : 'desktop'} ${fontSuit.variable} antialiased`}>
                <AppWrapper>{children}</AppWrapper>
            </body>
        </html>
    );
}
